# Generated by Django 4.2.3 on 2024-01-23 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEmployee', '0002_employee_address_employee_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEmployee.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
