# Generated by Django 4.2.3 on 2024-01-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEmployee', '0003_absence_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEmployee.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
