# Generated by Django 4.2.3 on 2024-01-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEmployee', '0004_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
