# Generated by Django 4.2.3 on 2023-12-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0002_client_employee_materialtransfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='code',
        ),
    ]
