# Generated by Django 4.2.3 on 2023-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0003_remove_center_code_remove_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', 'Matieres Premiére'), ('2', 'Final')], max_length=1, null=True),
        ),
    ]
