# Generated by Django 4.2.3 on 2023-12-24 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0008_remove_client_state_commande_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
