# Generated by Django 4.2.3 on 2023-12-24 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0009_commande_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
