# Generated by Django 4.2.3 on 2023-12-24 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0010_alter_commande_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArriveInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrive', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_arrive', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.commande')),
            ],
        ),
    ]
