# Generated by Django 4.2.3 on 2023-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0011_arriveinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='state',
            field=models.CharField(choices=[('1', 'En attente'), ('3', 'Livrée'), ('4', 'Annulée'), ('2', 'Partiellement arrivée')], default='1', max_length=1),
        ),
    ]
