# Generated by Django 4.2.3 on 2023-12-24 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0012_product_quantity_in_stock_alter_commande_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
                ('transfer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.arriveinstock')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.center')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialTransfer',
        ),
    ]
