# Generated by Django 4.2.3 on 2023-12-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0013_transfer_delete_materialtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.center')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.product')),
            ],
            options={
                'unique_together': {('product', 'location')},
            },
        ),
    ]
