# Generated by Django 5.0 on 2023-12-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0014_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Avrege_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
