# Generated by Django 5.0 on 2023-12-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0015_product_avrege_quantity_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gestionStockenv/Lib/admin_soft/static/img/'),
        ),
    ]
