# Generated by Django 5.0 on 2023-12-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0019_commande_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
