# Generated by Django 5.0 on 2023-12-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0021_paymentsupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_cost',
        ),
    ]
