# Generated by Django 4.2.3 on 2024-01-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0029_commande_payed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
