# Generated by Django 4.2.3 on 2024-01-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0032_alter_sale_sale_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
