# Generated by Django 4.2.3 on 2024-01-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0033_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.center'),
        ),
    ]
