# Generated by Django 4.2.3 on 2024-01-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0036_remove_arriveinstock_quantity_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriveinstock',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
