# Generated by Django 4.2.3 on 2024-01-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0037_arriveinstock_quantity_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriveinstock',
            name='quantity_in_stock',
        ),
    ]
