# Generated by Django 4.2.3 on 2024-01-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0038_remove_arriveinstock_quantity_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('Out of stock', 'Out of stock')], max_length=100),
        ),
    ]
